deployments:
  MyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  aat:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  bua:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  cog:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  demp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  ert:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  fghfd:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  gdfef:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  hnkm:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  inkm:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  jnkm:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  knkm:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  lnkm:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  mnkm:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  nnkm:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  onkm:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  pnkm:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  qnkm:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  rnkm:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  snkm:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding: 
       80:3000
  
